# DO NOT EDIT! This file was auto-generated by 'update-import-all-defaults' because the file '.nix-import-all' is inside this directory
{
  imports = [
    ./attic-watch.nix
    ./jellyfin-rpc.nix
    ./monado.nix
    ./mullvad.nix
    ./openrgb.nix
    ./p2p-clipboard.nix
    ./tagtime.nix
  ];
}
