# DO NOT EDIT! This file was auto-generated by 'update-import-all-defaults' because the file '.nix-import-all' is inside this directory
{
  imports = [
    ./age.nix
    ./configuration.nix
    ./home.nix
    ./xfconf.nix
    ./programs
    ./services
    ./unified
    ./wayland
    ./xsession
  ];
}
