# DO NOT EDIT! This file was auto-generated by 'update-import-all-defaults' because the file '.nix-import-all' is inside this directory
{
  imports = [
    ./difftastic.nix
    ./direnv.nix
    ./_enable.nix
    ./firefox.nix
    ./git.nix
    ./keepassxc.nix
    ./mangohud.nix
    ./nix-index.nix
    ./rofi.nix
    ./ssh.nix
    ./vscode.nix
    ./i3status-rust
    ./wezterm
  ];
}
