# DO NOT EDIT! This file was auto-generated by 'update-import-all-defaults' because the file '.nix-import-all' is inside this directory
{
  imports = [
    ./_enable.nix
    ./fzf.nix
    ./git.nix
    ./keepassxc.nix
    ./mangohud.nix
    ./nix-index.nix
    ./ripgrep.nix
    ./rofi.nix
    ./starship.nix
    ./vscode.nix
    ./zoxide.nix
    ./zsh.nix
    ./i3status-rust
  ];
}
