# DO NOT EDIT! This file was auto-generated by 'update-import-all-defaults' because the file '.nix-import-all' is inside this directory
{
  imports = [
    ./cloud-init.nix
    ./docker.nix
    ./fingerprint.nix
    ./graphical.nix
    ./hypervisor.nix
    ./luks-tpm2.nix
    ./managed-password.nix
    ./metrics-exporter.nix
    ./wakeonlan.nix
    ./yubikey.nix
  ];
}
