# DO NOT EDIT! This file was auto-generated by 'update-import-all-defaults' because the file '.nix-import-all' is inside this directory
{
  imports = [
    ./ledmatrix-widgets.nix
    ./libvirt-autoballoon.nix
    ./snapclient.nix
    ./pipewire
    ./wyoming
  ];
}
