name: Update inputs
on:
  workflow_dispatch:
  schedule:
    # UTC
    - cron: '0 4 * * *'

jobs:
  update_inputs:
    runs-on: native
    name: Update flake inputs
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: ryanccn/attic-action@v0.3.1
        with:
          endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          cache: ${{ secrets.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}
      - name: Running CI
        run: nix run .#__ci__update
        env:
          CI: true
