{
  lib,
  config,
  pkgs,
  ...
}:
with lib;
let
  cfg = config.my.programs.variety;
in
{
  config = mkIf cfg.enable {
    home.packages = with pkgs; [
      variety
      feh
    ];

    home.activation.variety-scripts =
      let
        setWallpaperScript = pkgs.writeShellApplication {
          name = "variety-set-wallpaper";
          runtimeInputs = with pkgs; [
            feh
          ];
          text = ''
            # !!! This script is auto-generated by home-manager !!!
            #
            # This script is based on the default variety set-wallpaper script

            WP="$1"
            # shellcheck disable=SC2034  # Unused variables left for readability
            TRIGGER="$2"
            # shellcheck disable=SC2034  # Unused variables left for readability
            ORIGINAL_WP="$3"
            # shellcheck disable=SC2034  # Unused variables left for readability
            MODE="$4"

            # echo "WP:           $WP"
            # echo "TRIGGER:      $TRIGGER"
            # echo "ORIGINAL_WP:  $ORIGINAL_WP"
            # echo "MODE:         $MODE"

            # DISPLAY_MAX=$(($(xrandr --listactivemonitors | wc -l)-2))
            # for i in $(seq 0 $DISPLAY_MAX); do
            #   nitrogen --set-zoom-fill --save --head=$i "$WP" 2> /dev/null
            # done

            feh --bg-fill "$WP" 2> /dev/null

            # XFCE / Lock Screen
            command -v xfconf-query >/dev/null 2>&1
            rc=$?
            if [[ $rc = 0 ]] ; then
                for i in $(xfconf-query -c xfce4-desktop -p /backdrop -l | grep -E -e "screen.*/monitor.*image-path$" -e "screen.*/monitor.*/last-image$"); do
                    xfconf-query -c xfce4-desktop -p "$i" -n -t string -s "" 2> /dev/null
                    xfconf-query -c xfce4-desktop -p "$i" -s "" 2> /dev/null
                    xfconf-query -c xfce4-desktop -p "$i" -s "$WP" 2> /dev/null
                done
            fi
          '';
        };
      in
      lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        run mkdir $VERBOSE_ARG \
            --parents $HOME/.config/variety/scripts
        run cp $VERBOSE_ARG \
            --force ${getExe setWallpaperScript} $HOME/.config/variety/scripts/set_wallpaper
      '';
  };
}
