# DO NOT EDIT! This file was auto-generated by 'update-import-all-defaults' because the file '.nix-import-all' is inside this directory
{
  imports = [
    ./_enable.nix
    ./gnome.nix
    ./k3s.nix
    ./libinput.nix
    ./xserver
  ];
}
