# DO NOT EDIT! This file was auto-generated by 'update-import-all-defaults' because the file '.nix-import-all' is inside this directory
{
  imports = [
    ./cloud-init.nix
    ./docker.nix
    ./fingerprint.nix
    ./graphical.nix
    ./luks.nix
    ./managed-password.nix
    ./metrics-exporter.nix
    ./secureboot.nix
    ./store-caching.nix
    ./swap.nix
    ./vm-guest.nix
    ./wakeonlan.nix
    ./yubikey.nix
    ./hypervisor
  ];
}
