# DO NOT EDIT! This file was auto-generated by 'update-import-all-defaults' because the file '.nix-import-all' is inside this directory
{
  imports = [
    ./envision.nix
    ./gamemode.nix
    ./godot.nix
    ./lutris.nix
    ./steam.nix
  ];
}
