# DO NOT EDIT! This file was auto-generated by 'update-import-all-defaults' because the file '.nix-import-all' is inside this directory
{
  imports = [
    ./accounts.nix
    ./assets.nix
    ./identity.nix
    ./imprinting.nix
    ./secrets.nix
  ];
}
