#!/usr/bin/env bash

set -o nounset
set -o errexit

_imprintingFile="$1"

_privateSshKeyFile=$(mktemp)
cat > "$_privateSshKeyFile"
_privateSshKey=$(cat "$_privateSshKeyFile")
_publicSshKey=$(ssh-keygen -f "$_privateSshKeyFile" -y)
rm "$_privateSshKeyFile"
echo "$_privateSshKey" | rage -e -R "$_imprintingFile" -o ./ssh_host_ed25519.age
echo -n "$_publicSshKey" > ./ssh_host_ed25519.pub
cat << EOF > ./imprinting.nix
{
  age = {
    imprinting.imprintingFile = ./ssh_host_ed25519.age;
    rekey.hostPubkey = "${_publicSshKey}";
  };
}
EOF
