#!/usr/bin/env bash

set -o nounset
set -o errexit

_imprintingFile="$1"
_name="$2"

_privateSshKeyFile=$(mktemp)
rm "$_privateSshKeyFile"
ssh-keygen -C "root@${_name}" -f "${_privateSshKeyFile}" -N "" -t ed25519
_privateSshKey=$(cat "$_privateSshKeyFile")
_publicSshKey=$(ssh-keygen -f "$_privateSshKeyFile" -y)
rm "$_privateSshKeyFile"
rm "${_privateSshKeyFile}.pub"

echo "$_privateSshKey" | rage -e -R "$_imprintingFile" -o ./ssh_host_ed25519.age
echo -n "$_publicSshKey" > ./ssh_host_ed25519.pub
cat << EOF > ./imprinting.nix
{
  age = {
    imprinting.imprintingFile = ./ssh_host_ed25519.age;
    rekey.hostPubkey = "${_publicSshKey}";
  };
}
EOF
