#!/usr/bin/env bash

set -o nounset
set -o errexit

_commit="$1"
_input="${2-nixpkgs-unstable}"
_flakeLock="${FLAKE_ROOT-.}/flake.lock"

_currentCommit=$(jq -r '.nodes[$INPUT].locked.rev' --arg INPUT "$_input" "$_flakeLock")
if [[ "$_currentCommit" == "$_commit" ]]; then
  echo "$_input in $_flakeLock is already on commit $_commit"
  exit 0
fi

_flakeUrl="github:NixOS/nixpkgs/${_commit}"
_hash=$(nix flake prefetch --json "$_flakeUrl" | jq -r '.hash')
_timestamp=$(date +%s)

cat "$_flakeLock" \
  | jq '{ nodes: .nodes * { $INPUT: { locked: {rev: $COMMIT, narHash: $HASH, lastModified: $TIMESTAMP } } }, root, version }' \
      --arg INPUT "$_input" --argjson TIMESTAMP "$_timestamp" --arg COMMIT "$_commit" --arg HASH "$_hash" \
  | sponge "$_flakeLock"
echo "Updated $_input in $_flakeLock to commit $_commit with hash $_hash"
