# DO NOT EDIT! This file was auto-generated by 'update-import-all-defaults' because the file '.nix-import-all' is inside this directory
{
  imports = [
    ./networking.nix
    ./nix.nix
    ./stylix.nix
    ./boot
    ./environment
    ./home-manager
    ./programs
    ./services
    ./specials
    ./unified
    ./virtualisation
  ];
}
