# DO NOT EDIT! This file was auto-generated by 'update-import-all-defaults' because the file '.nix-import-all' is inside this directory
{
  imports = [
    ./ftp.nix
    ./gitea.nix
    ./monado.nix
    ./mullvad.nix
    ./openrgb.nix
    ./opentabletdriver.nix
    ./p2p-clipboard.nix
    ./qemuGuest.nix
    ./samba.nix
    ./spice-autorandr.nix
    ./spice-vdagentd.nix
    ./ssh.nix
    ./swapspace.nix
    ./softether-vpn-server
  ];
}
